# Generated by Django 4.2 on 2026-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('electronics', '전자기기'), ('fashion', '패션'), ('book', '도서'), ('sports', '스포츠'), ('etc', '기타')], default='etc', max_length=20)),
                ('status', models.CharField(choices=[('on_sale', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='on_sale', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
